### ISSUE TITLE
Problem in getting data in content.json

### ISSUE THREAD

**Issue by AkashRajvanshi** [smallwat3r/smallwat3r.github.io#2]
Hey,
 I try this and it successfully fetches my GitHub data but  it creates problem to fetch in content.json (**shows network error on console**)

**Comment by smallwat3r** [comment]
Hi @AkashRajvanshi can you please share more information on the error you're getting? Thanks

**Comment by AkashRajvanshi** [comment]
![error](https://user-images.githubusercontent.com/30198030/73447295-69eb6500-4384-11ea-996b-eaf65d6135e2.png)
when I run this in my local system it shows me like this. how to fetch details in `content.js`

**Comment by smallwat3r** [comment]
The browser is loading this file from a local directory on your laptop, this will trigger a cross-origin error. If you want to run this from your local computer you will have to serve the files from a web-server.

I recommend using `http-server`.

Install using npm 
```sh
npm install http-server -g
```
Then cd outside the repository and run
```sh
# http-server <repo name>
http-server smallwat3r.github.io
```
You can visit the website on http://127.0.0.1:8080
